name: Build and Upload SDK

on:
  push:
    branches:
      - cuda
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch name (e.g., cuda)"
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  amd64:
    uses: canonical/sdkcraft-actions/.github/workflows/upload.yml@main
    with:
      runs-on: '["ubuntu-24.04"]'
      platforms: '["ubuntu@24.04:amd64"]'
      platform-flag: "--platform"
      track: "latest"
      risk: "stable"
      branch: "cuda"
    secrets:
      SDKCRAFT_STORE_CREDENTIALS: ${{ secrets.SDKCRAFT_STORE_CREDENTIALS }}
  arm64:
    uses: canonical/sdkcraft-actions/.github/workflows/upload.yml@main
    with:
      runs-on: '["self-hosted","Linux","ARM64"]'
      platforms: '["ubuntu@24.04:arm64"]'
      platform-flag: "--platform"
      track: "latest"
      risk: "stable"
      branch: "cuda"
    secrets:
      SDKCRAFT_STORE_CREDENTIALS: ${{ secrets.SDKCRAFT_STORE_CREDENTIALS }}
